//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Browser.rc
//
#define IDFILELOAD                      2
#define IDD_ABOUTBOX                    100
#define IDD_FTP                         101
#define CG_IDD_CHATDLG                  102
#define IDS_PROPSHT_CAPTION             103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROPPAGE1                   105
#define CG_ID_VIEW_CHATDLG              105
#define IDD_SETALARM_PROPERTY           105
#define IDD_PROPPAGE2                   106
#define CG_ID_VIEW_INFOBAR              106
#define IDD_SETHOMEPAGE_PROPERTY        106
#define IDR_MAINFRAME                   128
#define IDR_BROWSETYPE                  129
#define IDD_CONNECT_DIALOG              131
#define IDB_TOOLBARBITMAP               132
#define IDD_INPUT                       133
#define IDR_CONTEXTGRAPHIC              134
#define IDD_MOVIEPLAY                   137
#define IDR_FUTURE                      138
#define IDR_LINKBAR                     146
#define IDR_LINKMENU                    148
#define IDR_TOOLBAR1                    149
#define IDR_KOREANSONG                  151
#define IDD_ALARMOPTION                 152
#define CG_IDD_INFOBAR                  153
#define IDD_OMOK_ABOUTBOX               154
#define IDB_SPLASH                      158
#define IDB_BITMAP1                     160
#define IDB_DOWNLOAD                    160
#define IDB_UPLOAD                      161
#define IDR_GAMEMENU                    162
#define IDR_OMOKMENU                    163
#define IDC_FILELIST_LISTBOX            1000
#define IDC_RADIO_SERVERCLIENT          1000
#define IDC_COMBOURL                    1001
#define IDC_ADDRESS_COMBOBOX            1001
#define IDC_RADIO_SERVERCLIENT2         1001
#define IDC_PLAY                        1002
#define IDC_FILE_LIST_STATIC            1002
#define IDC_ADDRESS_STATIC              1003
#define IDC_COMBO_IP                    1003
#define IDC_END                         1004
#define IDC_USER_STATIC                 1004
#define IDC_PAUSE                       1005
#define IDC_NAME_COMBOBOX               1006
#define IDC_EDIT_SEND_MSG               1006
#define IDC_EDIT_RECEIVE_MSG            1007
#define IDC_LOCPROGRESS                 1008
#define IDC_VIDEO                       1009
#define IDC_UPLOAD_BUTTON               1009
#define IDC_ENDDIALOG                   1010
#define IDC_DOWNLOAD_BUTTON             1010
#define IDC_CONNECT_BUTTON              1011
#define IDC_SLIDER1                     1012
#define IDC_PLAYSLIDER                  1012
#define IDC_LOCALLIST_STATIC            1012
#define IDC_COMBO1                      1013
#define IDC_LOCALLIST_LISTBOX           1013
#define IDC_STATIC_SU                   1013
#define IDC_PASSWORD_EDIT               1014
#define IDC_MANAGEADDRESS_LIST          1016
#define IDC_INPUTNAME_STATIC            1017
#define IDC_SPINHOUR                    1017
#define IDC_INPUTNAME_EDIT              1018
#define IDC_HOUREDIT                    1018
#define IDC_SPINMINUTE                  1019
#define IDC_MINUTEEDIT                  1020
#define IDC_HOUR                        1021
#define IDC_MINUTE                      1022
#define IDC_ALARMCHECK                  1023
#define IDC_SETALARMMUSIC               1024
#define IDC_STATICHELP3                 1026
#define IDC_BUTTONHELP                  1026
#define IDC_STATICHELP                  1027
#define IDC_SETHOMEPAGE_EDIT            1028
#define IDC_STATICHELP2                 1029
#define IDC_STATICHELP4                 1030
#define IDC_STATICHELP5                 1031
#define IDC_STATICHELP6                 1032
#define IDC_STATICHELP7                 1033
#define IDC_STATICHELP8                 1034
#define ID_BACK                         32771
#define ID_NEXT                         32772
#define ID_HOME                         32773
#define ID_STOP                         32774
#define ID_FRESH                        32775
#define ID_MENU_VIEWER                  32777
#define ID_FULLSCREEN                   32779
#define ID_CLEARLEFTVIEW                32780
#define ID_CLEAR                        32781
#define ID_AVI                          32783
#define ID_MENU_VIEWER_INSPLIT          32785
#define ID_SEARCHSITE                   32786
#define ID_FAVORITESITE                 32788
#define ID_INTERFACESITE                32789
#define ID_SEARCH_DAUM                  32790
#define ID_SEARCH_NAVER                 32791
#define ID_SEARCH_EMPAS                 32792
#define ID_SEARCH_GOOGLE                32793
#define ID_SEARCH_ALTAVISTA             32794
#define ID_SEARCH_LYCOS                 32795
#define ID_SEARCH_MSN                   32796
#define ID_SEARCH_YAHOO                 32797
#define ID_SEARCH_CHOL                  32798
#define ID_SEARCH_DREAMWIZ              32799
#define ID_SEARCH_HANMIR                32800
#define ID_SEJONGSITE                   32801
#define ID_DAUMSITE                     32802
#define ID_BUTTON32804                  32804
#define ID_ALLSEE                       32806
#define ID_ALLFTP                       32807
#define ID_ADDFAVORITE                  32808
#define ID_CAPTURESCREEN                32809
#define ID_TRAY_ICON                    32810
#define ID_CONFIRM                      32811
#define ID_GAMEMENU                     32814
#define ID_GAME_OMOK                    32815
#define ID_CONNECT_IP                   32816
#define ID_STRETCHIMAGE                 32816
#define ID_CONNECT_DISCONNECT           32817
#define ID_WEBSITE                      61446
#define ID_OPTION                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1029
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
